name: Release Draft

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.35.6"
  RUST_VERSION: "1.84.1"

jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(sed -n 's/^version: \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p' app/pubspec.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build_windows_zip_x86_64:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Fix long file paths
        run: git config --system core.longpaths true

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - name: Dependencies
        working-directory: app
        run: flutter pub get

      - name: Compile for Windows
        working-directory: app
        run: flutter build windows -v

      - name: Create empty settings.json
        working-directory: app
        run: echo {} > build/windows/x64/runner/Release/settings.json

      - name: Add DLL files
        working-directory: app
        run: |
          Copy-Item ../scripts/windows/x64/msvcp140.dll build/windows/x64/runner/Release/
          Copy-Item ../scripts/windows/x64/vcruntime140.dll build/windows/x64/runner/Release/
          Copy-Item ../scripts/windows/x64/vcruntime140_1.dll build/windows/x64/runner/Release/

      - name: Zip compiled files
        working-directory: app
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath LocalSend.zip

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip-x86-64-result
          path: app/LocalSend.zip

  build_windows_zip_arm64:
    needs: build
    runs-on: windows-11-arm

    steps:
      - name: Fix long file paths
        run: git config --system core.longpaths true

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "master"
          cache: true

      - name: Dependencies
        working-directory: app
        run: flutter pub get

      - name: Compile for Windows ARM64
        working-directory: app
        run: flutter build windows -v

      - name: Create empty settings.json
        working-directory: app
        run: echo {} > build/windows/arm64/runner/Release/settings.json

      - name: Add DLL files
        working-directory: app
        run: |
          Copy-Item ../scripts/windows/arm64/msvcp140.dll build/windows/arm64/runner/Release/
          Copy-Item ../scripts/windows/arm64/vcruntime140.dll build/windows/arm64/runner/Release/
          Copy-Item ../scripts/windows/arm64/vcruntime140_1.dll build/windows/arm64/runner/Release/

      - name: Zip compiled files
        working-directory: app
        run: Compress-Archive -Path build/windows/arm64/runner/Release/* -DestinationPath LocalSend.zip

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip-arm64-result
          path: app/LocalSend.zip

  release:
    needs:
      - build
      - build_windows_zip_x86_64
      - build_windows_zip_arm64
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Draft release
        id: draft_release
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ needs.build.outputs.version }}
          name: v${{ needs.build.outputs.version }}

      # WINDOWS ZIP (x86_64)
      - name: Download windows zip file
        uses: actions/download-artifact@v4
        with:
          name: windows-zip-x86-64-result
          path: windows-zip-x86-64-result

      - name: Copy zip file to root
        run: cp windows-zip-x86-64-result/*.zip result.zip

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: result.zip
          asset_name: LocalSend-${{ needs.build.outputs.version }}-windows-x86-64.zip
          asset_content_type: application/zip

      - name: Download windows zip file (ARM64)
        uses: actions/download-artifact@v4
        with:
          name: windows-zip-arm64-result
          path: windows-zip-arm64-result

      - name: Copy zip file to root (ARM64)
        run: cp windows-zip-arm64-result/*.zip result.zip

      - name: Upload Release Asset (ARM64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: result.zip
          asset_name: LocalSend-${{ needs.build.outputs.version }}-windows-arm64.zip
          asset_content_type: application/zip
